# Improved issue-labeler configuration for GitHub

# Critical issues
crash:
  - '^Crash Report|Crash ID: crash/|app (crashes|crashed|keeps crashing)|browser (crashes|crashed|keeps crashing)'

error:
  - 'error|exception|failed|failure|not working|doesn\'t work'

security:
  - 'security|vulnerability|CVE-|exploit|hack|unsafe|breach'

# Performance issues
performance:
  - 'slow|performance|lag|freeze|hung|memory leak|high (CPU|RAM) usage'

# Bug categories
ui-issue:
  - 'display|interface|UI|layout|theme|appearance|visual|rendering'

network-issue:
  - 'network|connection|download|upload|offline|DNS|proxy|VPN'

sync-issue:
  - 'sync|synchronization|syncing|bookmark sync|history sync'

# Feature requests
feature-request:
  - '^Feature Request|would be nice if|suggestion for|please add|can you add'

# OS-specific (enabled, with improved patterns)
OS/Linux:
  - 'OS[|:\s]+(Linux|Ubuntu|Debian|Fedora|CentOS|Arch|Manjaro|Mint)|Operating System:\s+(Linux|Ubuntu|Debian|Fedora|CentOS|Arch|Manjaro|Mint)|linux[-_]?version|uname[-_]?a'

OS/Windows:
  - 'OS[|:\s]+(Windows|Win|Win10|Win11|Windows 10|Windows 11)|Operating System:\s+(Windows NT|Windows 10|Windows 11)|windows[-_]?version|winver'

OS/macOS:
  - 'OS[|:\s]+(Mac OS|macOS|MacOS|Mac|OSX|Mac OS X|Monterey|Ventura|Sonoma)|Operating System:\s+(Mac OS X|macOS|Darwin)|sw_vers'

OS/Android:
  - 'OS[|:\s]+(Android)|Operating System:\s+Android|android[-_]?version|Android [0-9]+(\.[0-9]+)*'

OS/iOS:
  - 'OS[|:\s]+(iOS|iPadOS)|Device/OS:\s+(iPhone|iPad|iOS)|Operating System:\s+iOS|iOS [0-9]+(\.[0-9]+)*|iPadOS [0-9]+(\.[0-9]+)*'

# Browser versions
version/latest:
  - 'Version [0-9]+\.[0-9]+\.[0-9]+\.[0-9]+ \(Official Build\) \(64-bit\)|Latest version|Up to date'

version/outdated:
  - 'Version [0-9]+\.[0-9]+\.[0-9]+\.[0-9]+ \(Official Build\) \(64-bit\)|old version|outdated version'

# Priority levels
priority/high:
  - 'severe|critical|urgent|major|high priority|blocking|broken|unusable'

priority/medium:
  - 'moderate|medium|average|functional but problematic'

priority/low:
  - 'minor|cosmetic|low priority|slight|not critical'
